server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://35.207.216.26:3003/
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
        - id: fusion
          uri: http://35.207.216.26:9011/
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0